### PR TITLE
Feature/data acquisition description xml

### PR DESCRIPTION
**Pull request by beckolson**
This pull request is to add a new class: svkDataAcquisitionDescriptionXML. The only changes made to existing code are a very minor refactor of svkSatBandsXML to make it possible to initialize that object from an vtkXMLDataElement instance and a couple of minor tweaks to svkUtils relating to its XML methods. Additionally the doxygen file was updated to make external C methods visible in the documentation.

Tests were added to test the new functionality and all tests passed.

NOTE: All tabs were replaced with spaces in svkUtils.cc and is the source of the large number of whitespace changes seen in the diffs.

### CODE REVIEW

**Comment by jccrane** [comment]
@stojan-m: @beckolson: Stojan, Can you review Beck's changes to svkSatBandsXML?

**Comment by stojan-m** [comment]
A method was extracted in order to make the interface more flexible. It is a minor change which should influence the behavior. Looks good to me.

**Comment by jccrane** [comment]
Hi,

Does intToString(long val) work with both int and long int, or does it need to be overloaded for both types?

**Comment by beckolson** [comment]
I believe it should work for both. Whether the container is a long or an int the string representation should be the same.  Also all tests passed and it looks like quite a few things use this method so I think we would have seen something fail if there was an issue: https://github.com/SIVICLab/sivic/search?utf8=%E2%9C%93&q=IntToString&type=Code

**Pull request merged**
