### PR TITLE
Feature/git revision tool

### PR DESCRIPTION
**Pull request by beckolson**
This PR is to add a script called git_revision_tool.pl (see usage below). This script helps manage versions using git tags and can be used to increment the version number. Additionally I have updated our CMakeSivicInclude.cmake to use this new tool to determine the svk release number. The only disadvantage of the current approach is that the svk release number is set to 0.0.0 if the project is not being built in a git clone. This would only happen if the developer got the code via a tarball. I think this is acceptable considering the advantages of being about to auto-increment the revisions easily.

```
NAME
    git_revision_tool.pl

SYNOPSIS
        git_revision_tool.pl [-i increment_index -p print_index -b branch -n -v -h]

            -i  increment_index  Increment the revision by the given index.
            -p  print_index      Just print the given index of the current revision.
            -b  branch           The branch that tags should be made on.
                                                 (default=develop)
            -o                   Override the repository check. If not set the
                                 script will exit with an error if the user is not
                                 on the specified branch OR has any local changes.
            -v                   Verbose output.
            -h                   Print this message.

DESCRIPTION
        The purpose of this script is to provide a tool for using git tags to
        manage revisions in a given git project. It is assumed that the tool is
        run from within a git project. There are a few different ways this script
        can behave depending on the arguments used: 
    
            *If no arguments are specified then current revision number is printed. 
        The current revision is determined by getting all tags for the project, 
        parsing out only tags that are an arbitrary number of integers delimited 
        by '.' characters. For example 0.9.4 would be identified as a revision tag.
        Only the highest revision number is printed, and it is assumed that any
        additional digits in a revision number belong to a LATER revision. For
        example 0.9.4.0 would be later then 0.9.4.

            *If the -i flag is used then the current revision will be incremented
        at the specified index. For example if '-i 0' is set the first index will be
        incremented by one and all later indices are will be set to 0. The index
        specified must be greater than or equal to zero and less then or equal to
        the number of revision indices. If the index is set to the number of
        revision indices then an extra revision index will be added. For example
        if the current revision is 0.9.2 and the user specifies '-i 3' then the
        new revision will be 0.9.2.1. The new index is set to one rather then
        zero for clarity. This flag will trigger a check to make sure the user
        is on the correct branch for tagging and that there are no local changes.
        Adding the '-o' flag overrides this check.

            *If the -p flag is used then only the revision number at a specific
        index is printed. For example if the current version was 1.2.0 and the
        user ran with '-p 1' then only '2' would be printed.

```

### CODE REVIEW

**Comment by beckolson** [comment]
I just realized I put in this PR without running the tests! I'll go ahead and run them and then add the 'needs review' tag when that's done.

**Comment by beckolson** [comment]
Okay all tests are a go!

**Comment by jccrane** [comment]
Hi,
A couple minor thoughts.  
1. Would it make sense to add a convenience flag to increment the Major, Minor, or Path number used in CPACK?:  Maj.Min.Patch: 
SET(CPACK_PACKAGE_VERSION_MAJOR "${SVK_MAJOR_VERSION}")
SET(CPACK_PACKAGE_VERSION_MINOR "${SVK_MINOR_VERSION}")
SET(CPACK_PACKAGE_VERSION_PATCH "${SVK_PATCH_VERSION}")

2.  the .pl probably isn't necessary in the name, but fine either way.

3.  if this is part of SIVIC the new files should contain our copyright/license text.

**Comment by beckolson** [comment]
Thanks for the feedback! I have done the following:
*Removed .pl extension.
*Added the License into the script.
*Updated the -i and -p flags to accept the values "major", "minor", and "patch" which will increment index 0, 1, and 2 respectively. See new usage below.

```
NAME
    git_revision_tool

SYNOPSIS
        git_revision_tool [-i increment_index -p print_index -b branch -n -v -h]

            -i  increment_index  Increment the revision by the given index. 
                                 This must either be an integer or one of the
                                 following options:
                                    major (first index)
                                    minor (second index)
                                    patch (third index)

            -p  print_index      Just print the given index of the current revision.
                                 This must either be an integer or one of the
                                 following options:
                                    major (first index)
                                    minor (second index)
                                    patch (third index)

            -b  branch           The branch that tags should be made on.
                                                 (default=develop)
            -o                   Override the repository check. If not set the
                                 script will exit with an error if the user is not
                                 on the specified branch OR has any local changes.
            -v                   Verbose output.
            -h                   Print this message.

DESCRIPTION
        The purpose of this script is to provide a tool for using git tags to
        manage revisions in a given git project. It is assumed that the tool is
        run from within a git project. There are a few different ways this script
        can behave depending on the arguments used: 
    
            *If no arguments are specified then current revision number is printed. 
        The current revision is determined by getting all tags for the project, 
        parsing out only tags that are an arbitrary number of integers delimited 
        by '.' characters. For example 0.9.4 would be identified as a revision tag.
        Only the highest revision number is printed, and it is assumed that any
        additional digits in a revision number belong to a LATER revision. For
        example 0.9.4.0 would be later then 0.9.4.

            *If the -i flag is used then the current revision will be incremented
        at the specified index. For example if '-i 0' is set the first index will be
        incremented by one and all later indices are will be set to 0. The index
        specified must be greater than or equal to zero and less then or equal to
        the number of revision indices. If the index is set to the number of
        revision indices then an extra revision index will be added. For example
        if the current revision is 0.9.2 and the user specifies '-i 3' then the
        new revision will be 0.9.2.1. The new index is set to one rather then
        zero for clarity. This flag will trigger a check to make sure the user
        is on the correct branch for tagging and that there are no local changes.
        Adding the '-o' flag overrides this check.

            *If the -p flag is used then only the revision number at a specific
        index is printed. For example if the current version was 1.2.0 and the
        user ran with '-p 1' then only '2' would be printed.

```

**Pull request merged**
